#!/bin/bash

timestamp="$(date +%Y%m%d%H%M%S)"
targetbase="$HOME/screenshots"
mkdir -p $targetbase
[ -d $targetbase ] || exit 1
scrot $targetbase/$timestamp.png
xclip -selection clipboard -t image/png -i < $targetbase/$timestamp.png

echo "$targetbase/$timestamp.png"