#!/bin/bash

# Take a screenshot using scrot and save it to $targetbase.

timestamp="$(date +%Y%m%d%H%M%S)"
targetbase="/media/data/screenshots"
mkdir -p $targetbase
[ -d $targetbase ] || exit 1
scrot -s $targetbase/$timestamp.png
xclip -selection clipboard -t image/png -i < $targetbase/$timestamp.png

echo "$targetbase/$timestamp.png"